version: '3.8'

services:
  php:
    build: ./docker/php
    dockerfile: Dockerfile.prod
    volumes:
      - ./src:/var/www/
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/production.conf
      - ./src:/var/www/
    networks:
      - app-network
    depends_on:
      - php

  redis:
    image: redis:alpine
    networks:
      - app-network

  queue-worker:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    command: php /var/www/artisan queue:work --sleep=3 --tries=3
    volumes:
      - ./src:/var/www
    networks:
      - app-network
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
